### PR TITLE
Changes in UI

### LINKED ISSUE #20: Make the arrow fatter and aligned on `src/routes/+pages.svelte`
There is a comment in the said file which indicates which arrow we are talking about

### PR DESCRIPTION
**Pull request by firelop**
Fixed https://github.com/BotsOn-app/desktop_app/issues/20 by making the arrow fatter and adding cap in buttons.
I saw a problem when loading images in main page that I fixed by adding a lazy loading (with pulse animation) with images in BotCard.svelte.
I added "tauri" script to package.json to make dev easier and ".idea" to .gitignore to exclude JetBrains IDE files.

### CODE REVIEW

**Comment by astro-gad** [comment]
Seems LGTM. About the Arrow, I Cannot see how it renders but we will try to provide the related figma project (we are actually working on a new UI).

**Comment by firelop** [comment]
I don't know if it's the render you want but that's how it looks like:
Capture d’écran 2023-07-29 145718

**Comment by astro-gad** [comment]
> I don't know if it's the render you want but that's how it looks like:
> Capture d’écran 2023-07-29 145718
> 

Yes exactly. Do you have an idea about a way of making it fatter instead of bigger ? It seems a bit odd, it doesn't match the font imo.

**Comment by firelop** [comment]
Using the font instead of custom elements <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'> (using the cdn that can be of course replaced by local css). With svelte we don't have any access to the generated SVG element

**Comment by firelop** [comment]
This is how the lazy loading is working with "fast 3G" option in devtools.
https://github.com/BotsOn-app/desktop_app/assets/49453048/7aac34a9-c4ab-4c51-aa6f-ce78ea3e066a

**Comment by astro-gad** [comment]
> Using the font instead of custom elements <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'> (using the cdn that can be of course replaced by local css). With svelte we don't have any access to the generated SVG element

We can't access a "style" property and set the font size to bold ? (I don't remember tbh)

**Comment by astro-gad** [comment]
> This is how the lazy loading is working with "fast 3G" option in devtools.
> https://github.com/BotsOn-app/desktop_app/assets/49453048/7aac34a9-c4ab-4c51-aa6f-ce78ea3e066a
> 
> 

This is perfect

**Comment by firelop** [comment]
> size

I remembered that was possible only through font version not custom element that use SVG. Maybe I could give it a try ?

**Comment by astro-gad** [comment]
> > size
> 
> I remembered that was possible only through font version not custom element that use SVG. Maybe I could give it a try ?

BoxIcons uses SVG instead of font ? Well if it's so, I bet it won't work by using font-size

**Review by Nirbose — APPROVED** [review]

**Comment by firelop** [comment]
> > > size
> > 
> > I remembered that was possible only through font version not custom element that use SVG. Maybe I could give it a try ?
> 
> BoxIcons uses SVG instead of font ? Well if it's so, I bet it won't work by using font-size

There is a version that use a font. Look at boxicon doc. We could use this one instead. I don't know if it could work with this font version.

**Comment by astro-gad** [comment]
> > > > size
> > > 
> > > I remembered that was possible only through font version not custom element that use SVG. Maybe I could give it a try ?
> > 
> > BoxIcons uses SVG instead of font ? Well if it's so, I bet it won't work by using font-size
> 
> There is a version that use a font. Look at boxicon doc. We could use this one instead. I don't know if it could work with this font version.

Do as you please :) !

**Review by Zerbaib — APPROVED** [review]

**Comment by firelop** [comment]
I tried to use the webfont and we can't  make icons thicker either. Is it really important ? If it is we could integrate custom svg with a thicker arrow

**Comment by astro-gad** [comment]
> I tried to use the webfont and we can't  make icons thicker either. Is it really important ? If it is we could integrate custom svg with a thicker arrow

I think we will either create our own component library with the SVGs or just let it as is. Thanks tho

**Pull request merged**
