### PR TITLE
First PR. Updated whole project.

### PR DESCRIPTION
**Pull request by astro-gad**
Updated whole project from webpack bundler to Vitejs bundler.
Migrated all components from class-based components to function-based components.
Fixed routing.

### CODE REVIEW

**Comment by Nirbose** [comment]
Why did you name the main folder package? It remains the source code of the app so why not src?

**Comment by astro-gad** [comment]
Mainly because the template named it "package"
Although, there is a "src" folrder in the package one x)

**Comment by Nirbose** [comment]
Well, here goes the renown 😂

**Comment by astro-gad** [comment]
I will do what I can boss!

**Comment by astro-gad** [comment]
So I renamed it "lib" because it's called like this in many projects template like for Flutter

**Comment by Nirbose** [comment]
😂

**Comment by Nirbose** [comment]
But "lib" doesn't make much sense in this case ^^'

**Pull request merged**
